### ISSUE TITLE
I wish to contribute engineers.csv

### ISSUE THREAD

**Issue by barrywimlett** [EDCD/FDevIDs#51]
Its not 100% complete, but I thought I'd contribute what I have, in the hope others have the rest

**Comment by Tkael** [comment]
Was there supposed to be an attachment?

**Comment by barrywimlett** [comment]
[engineers.txt](https://github.com/EDCD/FDevIDs/files/5728730/engineers.txt)

**Comment by barrywimlett** [comment]
if I start a blueprints file do you want a new issue, or shall I just attach it ?

**Comment by bgol** [comment]
To be consistent you should use `id,name` as column header and the singular form for the filename `engineer.csv`. You could also add the market_id of the station where the engineer is to be found to the file, like:
```
id,market_id,name
300000,128673927,Didi Vatermann
300010,128674183,Bill Turner
300030,128674695,Broo Tarquin
300040,128674951,The Sarge
300050,128675207,Zacariah Nemo
300080,128675975,Liz Ryder
300090,128676231,Hera Tani
300100,128676487,Felicity Farseer
300110,128676743,Ram Tah
300120,128676999,Lei Cheung
300130,128677255,Petra Olmanova
300140,128677511,Colonel Bris Dekker
300150,128677767,Marsha Hicks
300160,128678023,Elvira Martuuk
300180,128678535,The Dweller
300200,128679047,Marco Qwent
300210,128679303,Selene Jean
300220,128679559,Professor Palin
300230,128679815,Lori Jameson
300250,128680327,Juri Ishmaak
300260,128680583,Tod 'The Blaster' McQuinn
300270,128680839,Tiana Fortune
300280,128681095,Mel Brandon
300290,128681351,Etienne Dorn
300300,128954244,Chloe Sedesi
```
If you want to contribute a file you normally would fork the repository, make the changes (eg add the file) to that repo and then make a pull request to the original repo with your changes.

**Comment by barrywimlett** [comment]
The whole branch pull request thing is very new to me - and I actually tried it. But either didn’t have permissions or just cocked it up.

TFS or SVN I can handle, git I am having to learn - and this seemed trivial enough a situation for me to feel safe trying ( in public ).

Thanks for the feedback

**Comment by barrywimlett** [comment]
@bgol 

You version of this file posted in the issue - looks much more complete than mine, are the IDs correct or is it 'a sample you knocked together' ? I just want to check before I copy those changes

**Comment by bgol** [comment]
They are the correct engineer and market IDs.

**Comment by barrywimlett** [comment]
two pull requested opened - hope I did them right

**Comment by robbyxp1** [comment]
As said, in the review, its not right. Closed request.  Are you still working on it.

**Comment by Tkael** [comment]
This one is mergeable even if the other isn't ready yet.
