### ISSUE TITLE
Reserve Levels

### ISSUE THREAD

**Issue by nixpulvis** [EDCD/FDevIDs#55]
I'm looking to contribute `ReserveLevel` to this collection. I'm honestly not 100% sure if it only applies to rings or not.

> ReserveLevel: (Pristine/Major/Common/Low/Depleted) – if rings present

https://elite-journal.readthedocs.io/en/latest/Exploration/

I'm happy to open a PR if this looks like a complete list. Otherwise, how else should I verify it's completion?

**Comment by robbyxp1** [comment]
Closed, old.
